Spree::Config.set(:allow_ssl_in_production => false)
Spree::Config.set(:logo => '/assets/store/querbeet_header.jpg')
Spree::Config.set(:address_requires_state => false)
Spree::Config.set(:products_per_page => 200)
Spree::Config.set(:checkout_zone => 'Deutschland')
Spree::Config.set(:html_invoice_logo_path => "store/querbeet_header.jpg")
Spree::Config.set(:shipping_instructions => true)
